### ISSUE TITLE
Here are a few suggestions for improvement if possible

### ISSUE THREAD

**Issue by sensuigit** [Timthreetwelve/GetMyIP#1]
Hello, thank you for writing such a good software, I have been using it for a few days and it is very good.
I usually use vpn to surf the Internet, so I need to know whether my IP is correct every time I turn on the computer.

Here are a few suggestions for improvement if possible:
1. When minimized, the icon can be displayed on the tray. The icon can be replaced by the national flag icon, so that you can immediately know the current IP belongs to the region and country.
2. When you minimize to the tray, you can hover the mouse to display a prompt. The content of the prompt is the basic information, including the IP region and country. This avoids having to open it every time.
3. The IP can be refreshed. For example, if I change the IP in the middle, can it be automatically recognized, or give a refresh button, so that I only need to open the software once when I work for a long time.
4. https://vpntesting.com/my-ip-address The actual reference example can be seen here. I used this software before, but they seem to have stopped supporting it and can’t use it anymore.
5. Thank you for the work you do

**Comment by Timthreetwelve** [comment]
@sensuigit I'm grateful for your suggestions. I have added the tray icon with configurable info in the tooltip. I've also added a refresh button at the top right of the main window and in the tray icon context menu. The flag icon is just a little beyond my capability, perhaps in a future  update.
