### ISSUE TITLE
Enhancement Request: export- / import settings

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#110]
### Brief summary of your request

export- / import settings

### Request details

Would love to have a option to export and import the settings.

**Comment by Timthreetwelve** [comment]
@CMTriX, do you want to have a backup for the settings or perhaps to copy the settings to other machines? 

Tell me more about how you would use this feature.

Tim

**Comment by CMTriX** [comment]
backup for the settings to use after full system reinstall.

**Comment by Timthreetwelve** [comment]
@CMTriX, thanks for the clarification. I hope that you didn't need a full system reinstall!

I'll investigate to see what I can do.

Tim

**Comment by Timthreetwelve** [comment]
@CMTriX  

Progress. 

![GetMyIP_2024-11-08_20-28-46](https://github.com/user-attachments/assets/4a21366e-da1b-49d7-9207-770ee2dcaa81)

**Comment by CMTriX** [comment]
AWESOME!

**Comment by Timthreetwelve** [comment]
@CMTriX, I updated the layout to accommodate another button that will write all the settings to the log file. That should be helpful to anyone that creates a bug report/issue.

I added 16 new strings to the en-US language file. If you would be so kind as to update Strings.nl-NL.xaml I would greatly appreciate it. The files are located [here](GetMyIP/Languages).

![2024-11-17_16-33-01](https://github.com/user-attachments/assets/20f1d1f3-110c-447a-b8fa-646f5a2de338)

**Comment by CMTriX** [comment]
<sys:String x:Key="Button_ExportSettings">Exporteer instellingen</sys:String>
<sys:String x:Key="Button_ExportSettingsToolTip">Exporteer huidige instellingen naar een bestand.</sys:String>
<sys:String x:Key="Button_ImportSettings">Importeer instellingen</sys:String>
<sys:String x:Key="Button_ImportSettingsToolTip">Importeer instellingen uit bestand.</sys:String>
<sys:String x:Key="Button_ListSettings">Toon instellingen (lijst)</sys:String>
<sys:String x:Key="Button_ListSettingsTooltip">Schrijf instellingen (lijst) naar log bestand</sys:String>
<sys:String x:Key="Button_OpenAppFolderToolTip">Open programma map in verkenner</sys:String>
<sys:String x:Key="Button_OpenSettings">Open instellingen</sys:String>
<sys:String x:Key="Button_OpenSettingsToolTip">Open het instellingen bestand</sys:String>
<sys:String x:Key="MsgText_Error_ExportingSettings">Fout bij het wegschrijven van het instellingen bestand.</sys:String>
<sys:String x:Key="MsgText_Error_ImportingSettings">Fout bij het importeren van het instellingen bestand.</sys:String>
<sys:String x:Key="MsgText_Error_SavingSettings">Fout bij wegschrijven instellingen bestand.</sys:String>
<sys:String x:Key="SettingsItem_EditSettingsWarning">Alle wijzigingen die u in het instellingenbestand aanbrengt terwijl de app actief is worden overschreven!</sys:String>
<sys:String x:Key="SettingsItem_ImportWarning">Het importeren van instellingen zorgt ervoor dat de applicatie opnieuw wordt opgestart!</sys:String>
<sys:String x:Key="SettingsSection_SettingsFile">Instellingen bestand</sys:String>
<sys:String x:Key="SettingsSubHead_SettingsFile">Toepassingsinstellingen importeren, exporteren, openen en weergeven</sys:String>

**Comment by Timthreetwelve** [comment]
Thank you!
