### ISSUE TITLE
Translation: "GetMyIP" or "Get My IP"

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/GetMyIP#121]
### Report a problem with a translation

@Timthreetwelve 

In Translation strings you use "Get My IP" when the app name is "GetMyIP".

What's the raeson to use "Get My IP" in translation strings?

### Contribute a translation

```shell
I believe that in translation strings "Get My IP" should be "GetMyIP" (when it's related to the app).
```

### If this is a contribution, enter the language name and code

Italian (it-IT)

### If you wish to have your contribution acknowledged

bovirus

**Comment by Timthreetwelve** [comment]
@bovirus, in my mind the application is named Get My IP. I have been diligent in referring to the application as Get My IP in the documentation, and in any part on the UI that displays the name.

The exceptions are the GitHub repo name and the namespaces, which do not allow spaces, and the executable file names.

Upon review, I see that GetMyIP was used as the application name in the Languages\Strings.xx-XX.xaml files, which I will be happy to update.

Thanks for bringing this to my attention.

Tim

**Comment by Timthreetwelve** [comment]
All of the language files now use Get My IP for the application name. 

I also found one instance in the Readme.txt file.

Thanks again,
Tim
