### ISSUE TITLE
Enhancement Request - Display IP as Tray Icon

### ISSUE THREAD

**Issue by ColumbusAI** [Timthreetwelve/GetMyIP#130]
### Brief summary of your request

QoL improvement for At-A-Glance View of IP

### Request details

Can it be added as an option to make replace the Tray Icon with the IP address? 

In linux indicator-IP does this as shown here: [https://www.maketecheasier.com/display-ip-address-system-tray-ubuntu/](https://www.maketecheasier.com/display-ip-address-system-tray-ubuntu/)

**Comment by CMTriX** [comment]
Could it be same request as: https://github.com/Timthreetwelve/GetMyIP/issues/17

**Comment by Timthreetwelve** [comment]
@ColumbusAI, thanks for taking an interest in Get My IP!

Unfortunately, Windows isn't as flexible as Linux regarding can be added to the system tray. Icons are the only thing that I can add and the size of the icon is limited. There's only room to display 2-3 characters at most in an icon, any more and the result would be unreadable,

The best that I can do for now is to display the IP address in a tooltip.

Tim

**Comment by ColumbusAI** [comment]
You���re so right, Tim. Thanks for the info and for your app!

 �

**Comment by Timthreetwelve** [comment]
FYI, as soon as I complete some maintenance on my other apps, I plan to see if I can implement #93.

Thanks,
Tim
