### ISSUE TITLE
Bug Report: ERROR Parsing JSON

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

Installed version
checkbox: open after install

error JSON

### Steps To Reproduce

Installed version
checkbox: open after install
ERROR JSON

If installed and option not checked, then no error.

### Version

0.8.1.0

### Windows Version

(all updates) Microsoft Windows 10.0.22621

### Relevant log output

```shell
2023/10/16 13:29:37.03 DEBUG  Discovering internal addresses took 71,78 ms
2023/10/16 13:29:37.22 ERROR  Error parsing JSON
System.NotSupportedException: This type of CollectionView does not support changes to its SourceCollection from a thread different from the Dispatcher thread.
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at GetMyIP.Helpers.IpHelpers.ProcessIPInfo(String json)
2023/10/16 13:29:37.36 ERROR  {"status":"success","continent":"xxxxxxxxxxxxx","country":"xxxxxxxx","regionName":"xxxxxxxxxxx","city":"xxxxxxxxxx","zip":"xxx","lat":xx"lon":xxxx,"timezone":"xxxxx","offset":xxxx,"isp":"xxxxxxx","as":"xxxxx.","asname":"xxxxxxxxxxx","query":"xxxxxxx"}
2023/10/16 13:29:44.83 DEBUG  Discovering external IP information took 8.010,81 ms
2023/10/16 13:29:49.77 DEBUG  Opening C:\Users\xxx\AppData\Local\Temp\T_K\GetMyIP.20231016.log in default application
```

### Anything else?

You can wash my car ;)

**Comment by CMTriX** [comment]
Obscured the information with xxxxx

**Comment by CMTriX** [comment]
JSON Error also coming when starting after install.

i closed, run the program again, the error temporly gone.

ill close, try  later again if error comes back.

**Comment by Timthreetwelve** [comment]
I just got it to give me the same error. It's intermittent. It might be hard to isolate.

**Comment by Timthreetwelve** [comment]
I may have figured it out.

**Comment by Timthreetwelve** [comment]
It figures that it would blow up again right before I was going to shut down and go to bed. At least I know something that didn't cause the problem. I'll take another run at it tomorrow afternoon. That's when I was going to wash cars. 😞

**Comment by Timthreetwelve** [comment]
I believe that I have this fixed. I've tested it over one hundred times and the problem hasn't reoccurred. The fix will be in the next release.
