### ISSUE TITLE
Enhancement Request - Multilingual UI

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#16]
### Brief summary of your request

Multilingual UI

### Request details

Canyou add multilingual support?

i can provide DUTCH language. If there are more people who can help with other languages, please reply!

**Comment by Timthreetwelve** [comment]
@CMTriX, the first version of Get My IP with multilingual support is nearly ready.  I don't _plan_ any changes or additions to the language files. There are currently 189 strings, with several in the About and Settings sections being unchanged from WUView. Be sure to check out [the wiki page](https://github.com/Timthreetwelve/GetMyIP/wiki/Contribute-a-Translation), I've made some changes from WUView. I figured out how to use a carriage return in a string, so watch out for ` &#13; ` in about 6 of the strings.  If you can submit a PR for Dutch I would appreciate it.

I've also added a display on the Language section of the settings page (green ellipse). It shows the number of strings in the current language file versus the number in the en-US file.
![GetMyIP_2023-10-22_16-38-28](https://github.com/Timthreetwelve/GetMyIP/assets/43152358/56b4ff8d-2814-433c-9f05-5b9362adad64)

No hurry, I still have a lot to do before I release version 0.9.0.

Thanks in advance.

Tim

**Comment by Timthreetwelve** [comment]
Sure, the en-US file is [here](https://github.com/Timthreetwelve/GetMyIP/blob/main/GetMyIP/Languages/Strings.en-US.xaml). 

Whenever your translation is ready, I'll add it in version 0.9.1.

Thanks again for contributing. 

Tim

**Comment by CMTriX** [comment]
[GETMYIP_Strings.nl-NL.zip](https://github.com/Timthreetwelve/GetMyIP/files/13125697/GETMYIP_Strings.nl-NL.zip)

**Comment by Timthreetwelve** [comment]
Thank you!

**Comment by bovirus** [comment]
@Timthreetwelve 

I believe that you can close this request.

**Comment by Vaso73** [comment]
Im send Slovak Translation

[GETMYIP_Strings.sk-SK .zip](https://github.com/Timthreetwelve/GetMyIP/files/13239425/GETMYIP_Strings.sk-SK.zip)


please check it out...

**Comment by bovirus** [comment]
@Vaso73 
Thanks. I will  add to the GetMyIP  language folder.

If you can and have time pelase complete also language for Windows Update Viewer

https://github.com/Timthreetwelve/WUView/tree/main/WUView/Languages

Thanks.
