### ISSUE TITLE
Enhancement Request - Show IP in Notification Area

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#17]
### Brief summary of your request

Show IP 4 / 6 in notification area 

### Request details

Option to show only the full IP adres in notification / icon area. on the taskbar

**Comment by Timthreetwelve** [comment]
If I understand correctly, would you like something like this?

![Screenshot 2023-10-18 142604](https://github.com/Timthreetwelve/GetMyIP/assets/43152358/b38c7016-7e4b-47b5-9b5e-13244640b4ba)

**Comment by CMTriX** [comment]
yes, but the ip must be in notification area in stead of the [ip] logo.

**Comment by Timthreetwelve** [comment]
I don't think that is possible since it needs to be an icon.

**Comment by CMTriX** [comment]
Is the icon a image?
1. create/write new image with ip
2. reload image in notification area.
3. if new ip (vpn connections) goto step 1

**Comment by Timthreetwelve** [comment]
Yes, the icon is an image. Windows determines the icon size, which is about 20x20 pixels. It's just not practical to try to fit an IP address in an icon. I even considered using 4 icons, one for each octet, but I wouldn't be able to ensure that they would display in the correct order.

I'm sorry to disappoint, but it looks like a tooltip above the icon is the best that I can do.

Tim

**Comment by CMTriX** [comment]
okay! Put it on your TODO list :P  (if you want)
thank you

**Comment by Timthreetwelve** [comment]
👍🏻
