### ISSUE TITLE
Bug Report: shortcuts not removed after uninstall

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

When uninstalling, the shortcut icon is not removed.

### Version

0.9.0

### Windows Version

(all updates) Microsoft Windows 10.0.22621

**Comment by Timthreetwelve** [comment]
@CMTriX Where is the shortcut icon? Desktop? Start Menu? Elsewhere?

**Comment by CMTriX** [comment]
Uninstalled again: Desktop **shortcut** not removed.

**Comment by Timthreetwelve** [comment]
I've updated the setup script to delete the GetMyIP desktop shortcuts. Of course, this functionality won't work until the next version is uninstalled. Also, during my testing I had to refresh the desktop before the icon actually disappeared.  

This change will be included in the next release.

Tim

**Comment by bovirus** [comment]
@Timthreetwelve 

I believe that you can close this ticket.
