### ISSUE TITLE
Enhancement Request - Inno Setup script

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/GetMyIP#24]
### Brief summary of your request

Improvements about installer Inno Setup script

### Request details

@T

I have some request about current installer script

"View the ReadMeFile" is untranslated

Why did yoiu use this string

SetupWindowTitle = Setup - {#MyAppName} {#MyAppVersion}

that means to show "Setup - xxx xxxx" also in Italian?
The stringID "SetupWindowTitle" is already localized in each .isl Inno Setup language file.

Is missing "UninstallDisplayName="
Is missing "AppSupportURL="
I missing "AppUpdatesURL="
 
The value "https://github.com/Timthreetwelve/GetMyIP" can be set through define
The value "EBEA37CE-1C9C-44C2-ACE3-102E6BF79364" (appID) can be set via define

Is missing "DeleteConfigFiles" string text message
               mres := MsgBox(CustomMessage('DeleteConfigFiles'), mbConfirmation, MB_YESNO or MB_DEFBUTTON2)
 
Is missing  "AppIsRunning" string text message
        Answer := MsgBox(ThisApp + ' ' + CustomMessage('AppIsRunning'), mbError, MB_OKCANCEL);

Please define these two string in english.

If you agree I can post a PR for the Inno Setup script.

**Comment by Timthreetwelve** [comment]
Thanks for your help with this.
