### ISSUE TITLE
Enhancement Request - Use of external language file for translation testing

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/GetMyIP#26]
### Brief summary of your request

Use of external language file for translation testing

### Request details

@Timthreetwelve 

Please consider if you can use of external language file for testing localization.

Many time to have the option to test tarnslation in place befroe to upload language file in github is for me a plus.

**Comment by Timthreetwelve** [comment]
I like this idea. I'll see about implementing it after the current work in progress has been released.

**Comment by Timthreetwelve** [comment]
I made some progress on this today. I plan for it to be in the next release.

A file named Strings.test.xaml will be in the application's folder. Any number (or all) of the language strings can be in the file.

``` XML
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:sys="clr-namespace:System;assembly=mscorlib">

	<sys:String x:Key="NavTitle_Settings">Settings - Language Test</sys:String>

</ResourceDictionary>
```

The file is only read when the "Enable language testing" checkbox is checked. You can see in the screenshot that the title has changed.

![GetMyIP_2023-10-30_21-36-01](https://github.com/Timthreetwelve/GetMyIP/assets/43152358/6f7a1bb0-c09b-4600-b8a9-a5c5feb387ed)

You can also see that the navigation menu width issue has been fixed.

**Comment by Timthreetwelve** [comment]
Completed in release 0.9.3.

**Comment by bovirus** [comment]
@Timthreetwelve 

Thanks.
Please close the ticket.
