### ISSUE TITLE
Enhancement Request: Automatic update when network changes

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#30]
### Brief summary of your request

Automatic update when network changes

### Request details

As suggested by @CMTriX in #22

>autorefresh ip mouseover in taskbar when change detected (vpn) (optional popup new IP for a short time)

This is worth investigating and deserves its own issue.

### Anything else?

Not at this time

**Comment by Timthreetwelve** [comment]
@CMTriX 

In researching methods for updating the IP information I found that detecting an address change as it happened was problematic and unreliable. I was intrigued by your idea of checking on mouseover, but I couldn't make it happen. I decided to go with a time interval approach. The tooltip for the tray (notification area) icon will be updated every x minutes, as well as the external info page in the app. This is how it currently looks in settings:

![2023-11-18_21-25-19](https://github.com/Timthreetwelve/GetMyIP/assets/43152358/e9bb1643-ea99-44b2-b462-57bc588acf22)

I have tested it as far as I can, but I don't use a VPN or anything that would change my external IP address. Can you help with that? If you can, I may publish a "pre-release" version and let you see if there are any bugs before publishing a release.

I decided to use a Windows toast notification to notify the user if the IP address changes. The implementation of the toast notification required me to target the build to Windows 10 build 19041 or above. IF that causes problems, I may have to find another notification method. That's why I added `(experimental)`.

One last thing, I updated the [Language file tool](https://github.com/Timthreetwelve/CheckLanguageFile/releases/tag/v0.0.4)  and added a [grid](https://github.com/Timthreetwelve/CheckLanguageFile#screenshots) to the bottom of the file compare tab to make it more useful.

Thanks,
Tim

**Comment by CMTriX** [comment]
Yes you can send me the beta version for test.
You can also test local, change DNS in 1.1.1.1

**Comment by Timthreetwelve** [comment]
@CMTriX 

You can find it here https://github.com/Timthreetwelve/GetMyIP/releases/tag/0.9.5-beta

Thanks,
Tim

**Comment by CMTriX** [comment]
Thanks, running for 13 hrs now. 
when connection is down, there is a uggly windows (default windows box) error with NO CONNECTION
I like the autostart/minimize and refresh!

**Comment by Timthreetwelve** [comment]
@CMTriX 

Maybe a message box reporting that a connection is down needs to be ugly? 

I appreciate you giving it a long test and I'm happy that you like the recent additions. 😃

If you don't find any problems, I'd like to release the next version soon. There's a couple dozen new strings that need a translation. 

Tim

**Comment by CMTriX** [comment]
Yes, the box reports the connection is down, (not happen often..)
I read the new translation guide. If possible, just point me to the files that need update, i will translate asap so you can release 0.9.7

**Comment by Timthreetwelve** [comment]
Here's a link to the [Languages](https://github.com/Timthreetwelve/GetMyIP/tree/main/GetMyIP/Languages) folder. If you use the  [Language file tool](https://github.com/Timthreetwelve/CheckLanguageFile/releases/tag/v0.0.4) to compare the en-US file to the nl-NL file it's easy to spot the missing strings, they'll have a "misty-rose" background. (Sometimes color names crack me up.) 

Tim

**Comment by Timthreetwelve** [comment]
Thank you. My plan is to publish the next release sometime later tomorrow. Maybe.

Tim

**Comment by CMTriX** [comment]
If you build the language tool. Is it possible to load the 2 files.
in the left pane, filename from the loaded file, in the right pane the other filename.
When lines not found, sort them to top [button]
Option to enter/translate the missing (and other lines if needed). The missing lines auto added by the tool.
option to save the updated files. (left and right pane)

**Comment by Timthreetwelve** [comment]
@CMTriX 

I'm going to copy your last comment to a new Issue in the Check Language File repository and close this issue since the requested enhancements to Get My IP have been added to version 0.9.6.

Tim
