### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#32]
### Report a problem with a translation

@bovirus, are these two supposed to have the same translation?

``` XML
    <sys:String x:Key="External_ASName">Come Nome</sys:String>
    <sys:String x:Key="External_ASNumber">Come Nome</sys:String>
```

Also, in this context "AS" is an abbreviation for Autonomous System. 

Do the following need to be updated as well?

``` XML
    <sys:String x:Key="SettingsItem_ShowAsName">Visualizza come nome</sys:String>
    <sys:String x:Key="SettingsItem_ShowAsNumber">visualizza come numero</sys:String>
```

If the abbreviation is confusing, feel free to use Autonomous System.

**Comment by bovirus** [comment]
@Timthreetwelve 

Thanks. Fixed.

**Comment by Timthreetwelve** [comment]
Thanks
