### ISSUE TITLE
Bug Report: 0.9.2 - Feedback

### ISSUE THREAD

**Issue by bovirus** [Timthreetwelve/GetMyIP#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues (both open and closed).

### What happened or didn't happen?

Left side panel need to increase a few (Info programma truncated)
Right side panel is too short to show all etxt and IP logo
Pleasincrease default width for elft and right panel

Original size
![image](https://github.com/Timthreetwelve/GetMyIP/assets/1262554/73ca569a-2549-4b17-b84e-25e93415a1c0)

Incraesed size (show IP logo)
![image](https://github.com/Timthreetwelve/GetMyIP/assets/1262554/72304c7c-0a5b-486f-906d-4a7404f29d19)

Check box for full path of log file is not showed.
Increase default right panel width.
![image](https://github.com/Timthreetwelve/GetMyIP/assets/1262554/672072ed-dee5-46d0-835f-0976a05cdb4f)

In this context "Close" is better then "Cancel".
![image](https://github.com/Timthreetwelve/GetMyIP/assets/1262554/cd5e4b7c-6006-4c5f-b37f-e870e46285b1)

Asking to show map show this error with these untranslated strings,
![image](https://github.com/Timthreetwelve/GetMyIP/assets/1262554/dd2bf121-96c2-4b01-b9b9-4c105f1e5dac)

### Steps To Reproduce

Check screenshots

### Version

0.9.2

### Windows Version

Windows 22 H2 64bit italian

**Comment by Timthreetwelve** [comment]
@bovirus, I think that I have all of these issues addressed. 

I hope to have a new release ready sometime late in the day tomorrow, maybe the day after if I discover more issues.

**Comment by Timthreetwelve** [comment]
Complete in release 0.9.3.

**Comment by bovirus** [comment]
@Timthreetwelve 

Thanks.
Please close the ticket.
