### ISSUE TITLE
Language Testing Bug 🐞 

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#43]
### Report a problem with a translation

When using the language testing that was introduced in version 0.9.3, line breaks (carriage returns), expressed as `&#13;` are not being processed when read from the file at runtime. In other words, the line of text isn't breaking. When the same file (or string) is added as a resource and compiled, the line breaks work fine. Everything else about the test process works fine. 

Example:
``` xml
    <sys:String x:Key="MsgText_Error_TooManyRequests" xml:space="preserve">Error connecting.&#13;Too many requests.</sys:String>
```
Displays as: 
`Error connecting.Too many requests.`

When it should display as:
```
Error connecting.
Too many requests.
```
I'm thinking that it has something to do with the file being read at runtime vs being compiled as a resource. I've tried encoding the file as ANSI, UTF-8, UTF-8 with BOM, and UTF-16 with the same result.

This has me stumped at the moment. Reaching out for help. If someone has an idea, let me know.

In the meantime, language contributors should continue using language testing, but be aware that this is happening.

**Comment by CMTriX** [comment]
\n
\r

**Comment by Timthreetwelve** [comment]
Unfortunately, the standard newline characters don't work. They just get displayed.

It's not that much of a problem since it works correctly once the language is compiled. And it's only in GetMyIP. 

If a solution doesn't present itself, I'll just revert to the way I did it in WUView, which is to have two separate strings and not use the `&#13;`

**Comment by CMTriX** [comment]
Ok! 'Niet geschoten is altijd mis.'

**Comment by bovirus** [comment]
@Timthreetwelve

If you ahve a long string or multiperiod string could be an idea to have multile striongs like

<sys:String x:Key="SettingsItem_UseOSLanguageToolTipLine1">When this option is selected, the language specified in the Windows settings will</sys:String>
<sys:String x:Key="SettingsItem_UseOSLanguageToolTipLine2">be used if a translation is available, otherwise English (en-US) will be used.</sys:String>

**Comment by Timthreetwelve** [comment]
I will revert to the method of defining two or more strings. Fortunately, only this project uses the `&#13;`  I can probably get that done in less time than fixing the issue. That will be a good project for a cold, rainy day. 😉
