### ISSUE TITLE
Slovak Translation

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#44]
Moving this to a new issue

[GETMYIP_Strings.sk-SK .zip](https://github.com/Timthreetwelve/GetMyIP/files/13239425/GETMYIP_Strings.sk-SK.zip)

please check it out...

_Originally posted by @Vaso73 in https://github.com/Timthreetwelve/GetMyIP/issues/16#issuecomment-1790756869_

**Comment by bovirus** [comment]
@Timthreetwelve 

Copied the Slovak tarnsòation in GetMyIi language folder.

Add Slovak string in Inno Setup.

**Comment by Timthreetwelve** [comment]
Closing this issue, the language has been added to version 0.9.6.
