### ISSUE TITLE
A pause on translation work 

### ISSUE THREAD

**Issue by Timthreetwelve** [Timthreetwelve/GetMyIP#45]
### Report a problem with a translation

@bovirus @CMTriX @Vaso73

I dislike doing this, but I need to pause translation work on all the Timthreetwelve projects.

The current method of updating language files is too fragile. This problem is of my own making, and I need to devise a better way to deal with additions and updates. 

I honestly appreciate all the effort that everyone has put into the translations.

I have other obligations all day on Thursday, so I'll try to have an update on Friday.

Thank you for your patience and understanding.

Tim

**Comment by Timthreetwelve** [comment]
@bovirus @CMTriX @Vaso73 and anyone else concerned.

To make this a smoother process for everyone involved, it has become necessary to create new procedures. 
- Each new translation contribution or language file update must be associated with a pull request or a new translation issue.
- Only one language file per PR or issue. This will make it easier to deal with merge conflicts if/when they arise.
- Before submitting a new translation or an updated language file, the file must be checked using the new Check Language File tool found [here](https://github.com/Timthreetwelve/CheckLanguageFile). This new tool has two functions. It does file validation in the first tab. File comparison is in the second tab. Language files should be compared to the latest en-US file to check for missing keys.
- Missing keys should not be replaced with the en-US version of the key. Doing so will break the comparison process.
- Updates to a language file will no longer be added to the **bottom** of the file. Instead, they will be done in place and **comments** will be added to the bottom of the language file. Adding updates to the bottom was leading to too many duplicate keys. In addition, making changes in place makes it easier to see exactly what has changed when using a diff tool.
- These comments will have a header record that will note when the change was made. Here's an example of how the comments look now.
``` xml
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    LANGUAGE FILE UPDATES

    Additions, Deletions and Updates will be made in the appropriate sections above. Each change will
    be associated with a comment made below this block.

    Comment Format:
       There will be a header indicating when the change was made (date yyyy/mm/dd and UTC time).
       Modified lines will follow, one comment line per line changed.
       Comment lines use this syntax:  Change Type | Key Name

     Change type:
       A = Added
       D = Deleted
       U = Updated
       * = Comment not related to a single line
     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

    <!-- Begin changes on 2023/11/12 @ 20:00 UTC -->
    <!-- * | Updated comments in this file -->
    <!-- * | Moved all items to appropriate sections above -->
    <!-- U | About_Contribute -->
    <!-- U | MsgText_Error_Connecting -->
    <!-- * | About_LimitsToolTipLine has been changed to 2 lines -->
    <!-- D | About_LimitsToolTipLine -->
    <!-- A | About_LimitsToolTipLine1 -->
    <!-- A | About_LimitsToolTipLine2 -->
    <!-- U | MsgText_Error_JsonNull -->
    <!-- U | MsgText_Error_JsonParsing -->
    <!-- U | MsgText_Error_OpeningFile -->
    <!-- U | MsgText_Error_Settings -->
    <!-- U | MsgText_Error_TooManyRequests -->
    <!-- U | MsgText_TooltipNothingToDisplay -->
    <!-- U | SettingsItem_PermLogFileNameTooltip -->
    <!-- * | SettingsItem_PublicInfoProviderTooltip has been changed to 2 lines -->
    <!-- D | SettingsItem_PublicInfoProviderTooltip -->
    <!-- A | SettingsItem_PublicInfoProviderTooltipLine1 -->
    <!-- A | SettingsItem_PublicInfoProviderTooltipLine2 -->
    <!-- End changes on 2023/11/12  -->
```
- Changes to the language file will be noted in the comments. One comment per change.
- The comment syntax is `<!--` followed by the comment text, ending with `-->`. Comments must not contain two consecutive dash or hyphen `--` characters.

I hope that this is something that current, and future, contributors can live with.  As I said in the original issue "This problem is of my own making". I genuinely hope that nobody is offended by these changes.

With that being said, I have updated all the language files in the Get My IP repository. I removed the `&#13;` carriage returns from all language files. Most of the strings that had a carriage return were dealt with in code. There were two instances where one string was converted into two strings. Please check `About_LimitsToolTipLine` and `SettingsItem_PublicInfoProviderTooltip` to verify that they appear ok in your language. Also check the strings marked with a `U` in the comments. Use the new Check Language File tool. 😉

The "pause" has been lifted. Thank you for your patience and understanding.

Tim

**Comment by Timthreetwelve** [comment]
I've updated the language files in Get My IP and HWiNFO-VSB-Viewer. I've started in WUView but have not finished. TimVer will be next after WUView.

**Comment by CMTriX** [comment]
No problem, i will continue support with translation!
