### ISSUE TITLE
Enhancement Request - Add IP2Location.io API as one of the geolocation APIs

### ISSUE THREAD

**Issue by ip2location** [Timthreetwelve/GetMyIP#91]
### Brief summary of your request

Add IP2Location.io API as one of the geolocation APIs

### Request details

The [IP2Location.io API](https://www.ip2location.io/) has a limit of 500 IP queries per day if used without an API key. If using the free API plan key, there is a limit of 30,000 queries per month. It would be good to add this API as another option for your users.

**Comment by Timthreetwelve** [comment]
@ip2location, I took a quick look, and this looks like it's doable. I have some commitments for the next few days, so it will be the end of next week before I can start adding it.

Tim

**Comment by Timthreetwelve** [comment]
@ip2location, this has been added and will be in the next release. 

Tim
