### ISSUE TITLE
Enhancement Request: Tray icon double click 

### ISSUE THREAD

**Issue by CMTriX** [Timthreetwelve/GetMyIP#99]
### Brief summary of your request

Double Click 

### Request details

Is it posible to add a double click future to the tray icon so it opens the window? I now have to click with right mouse: and select SHOW WINDOW.

### Anything else?

not yet !

**Comment by Timthreetwelve** [comment]
@CMTriX 

No problem.  It will be in the next release.

Would you have time to update Strings.nl-NL.xaml in the [Languages Folder](https://github.com/Timthreetwelve/GetMyIP/blob/main/GetMyIP/Languages)? 

Thanks,
Tim

**Comment by CMTriX** [comment]
Yes thnx. Going to translate tomorow.

**Comment by CMTriX** [comment]
Translation updated.

**Comment by Timthreetwelve** [comment]
I've released the version with your enhancement request and your translation updates. Thanks a lot.

Tim
